manipulator:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_timeout: 0.005
  solve_type: Manipulation1

#manipulator:
#  kinematics_solver: pick_ik/PickIkPlugin
#  kinematics_solver_timeout: 0.005
#  kinematics_solver_attempts: 5
#  mode: global
#  position_threshold: 0.00001

#manipulator:
#  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#  kinematics_solver_search_resolution: 0.0050000000000000001
#  kinematics_solver_timeout: 0.0050000000000000001

robotiq_gripper:
  kinematics_solver: ""